version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: recommendations
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql

  spark:
    image: bitnami/spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8081"

  airflow-webserver:
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
    ports:
      - "8080:8080"
    volumes:
      - ./orchestration/dags:/usr/local/airflow/dags

  recommendation_api:
    build: ../model_serving
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - spark
